/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2018-09-20 05:35:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/mqtt/WebServer_final/WebServer/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebServer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1519644874033L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<link rel=\"icon\" href=\"logo.png\">\r\n");
      out.write("\r\n");
      out.write("<title>실시간 유동인구</title>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<!-- <link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"> -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<!-- <link href=\"dashboard.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://maps.google.com/maps/api/js?sensor=false\">\r\n");
      out.write("</script> -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.3.min.js\"></script>\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDo3Hex6WnJUr6NTdUiwl9pM3CGJs7OvlA&libraries=visualization\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.0/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"jquery.blockUI.js\"></script>\r\n");
      out.write("<script src=\"main1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/earlyaccess/notosanskr.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var selecMarker;\r\n");
      out.write("function clearText(y){ \r\n");
      out.write("\tif (y.defaultValue==y.value) \r\n");
      out.write("\t\ty.value = \"\" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toggleBounce() {\r\n");
      out.write("\tif(marker.getAnimation() != null) {\r\n");
      out.write("\t\tmarker.setAnimation(null);\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tmarker.setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function toggleHeatmap() {\r\n");
      out.write("\t/* heatmap.setMap(heatmap.getMap() ? null : map); */\r\n");
      out.write("\tif(heatmap.getMap()) {\r\n");
      out.write("\t\theatmap.setMap(null);\r\n");
      out.write("\t\ttoggleFlag = 0;\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\theatmap.setMap(map);\r\n");
      out.write("\t\ttoggleFlag = 1;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("var heatmap;\r\n");
      out.write("var map;\r\n");
      out.write("var toggleFlag = 0;\r\n");
      out.write("var heatMapArray = [];\r\n");
      out.write("var markers;\r\n");
      out.write("var event1;\r\n");
      out.write("var markerImage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\"newmarker.png\",\r\n");
      out.write("\t    null,null,null,\r\n");
      out.write("\t    new google.maps.Size(17, 24)\r\n");
      out.write("\t);\r\n");
      out.write("var carImage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\"sports-car.png\",\r\n");
      out.write("\t    null,null,null,\r\n");
      out.write("\t    new google.maps.Size(30, 30)\r\n");
      out.write("\t);\r\n");
      out.write("var listeners = [];\r\n");
      out.write("function initialize() {\r\n");
      out.write("\tvar latlng = new google.maps.LatLng(37.56017787685811,\r\n");
      out.write("\t\t\t126.98316778778997);\r\n");
      out.write("\tvar mapOptions = {\r\n");
      out.write("\t\t\tzoom : 11.35,\r\n");
      out.write("\t\t\tcenter : latlng,\r\n");
      out.write("\t\t\t//scrollwheel : true,\r\n");
      out.write("\t\t\t//draggable : false,\r\n");
      out.write("\t\t\tscaleControl : true,\r\n");
      out.write("\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t}\r\n");
      out.write("\tmap = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\r\n");
      out.write("\r\n");
      out.write("\t// heatmap\r\n");
      out.write("\theatmap = new google.maps.visualization.HeatmapLayer({\r\n");
      out.write("\t      data: heatMapArray,\r\n");
      out.write("\t      map: map\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tcurrent = new google.maps.LatLng(37.5640, 126.9751);\r\n");
      out.write("\tmarkers = new Array();\r\n");
      out.write("\ttimer = setInterval( function () {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"http://\"+address+\":8080/WebServer/LocationController\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t/* console.log(heatMapArray.length + \"==================== 1\"); */\r\n");
      out.write("\t\t\tif(listeners.length != 0) {\r\n");
      out.write("\t\t\t\tfor(var i=0; i<Object.keys(data).length; i++) {\r\n");
      out.write("\t\t\t\t\tlisteners[i].remove();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar latitude, longitude;\r\n");
      out.write("\t\t\tfor(var i=0; i<Object.keys(data).length; i++) {\r\n");
      out.write("\t\t\t\tclient_id = eval(\"data.c\"+i+\".client_id\");\r\n");
      out.write("\t\t\t\tlatitude = eval(\"data.c\"+i+\".latitude\");\r\n");
      out.write("\t\t\t\tlongitude = eval(\"data.c\"+i+\".longitude\");\r\n");
      out.write("\t\t\t\tvar current = new google.maps.LatLng(latitude, longitude);\r\n");
      out.write("\t\t\t\t/* heatMapArray[i] = current; */\r\n");
      out.write("\t\t\t\tif(toggleFlag == 1) {\r\n");
      out.write("\t\t\t\t\tif(markers[i]) {\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].setMap(null);\r\n");
      out.write("\t\t\t\t\t\theatMapArray[i] = markers[i].getPosition();\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\theatMapArray[i] = current;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif(markers[i]) {\r\n");
      out.write("\t\t\t\t\t\tif(!markers[i].getMap()) {\r\n");
      out.write("\t\t\t\t\t\t\tmarkers[i].setMap(map);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].setPosition(current);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tif (client_id == 'paho000011117') {\r\n");
      out.write("\t\t\t\t\t\t\tmarkers[i] = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\tposition : current,\r\n");
      out.write("\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : client_id,\r\n");
      out.write("\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : carImage\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tmarkers[i] = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\tposition : current,\r\n");
      out.write("\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : client_id,\r\n");
      out.write("\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : markerImage\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tmarkers[i].addListener('mouseover', function() {\r\n");
      out.write("\t\t\t\t\t\tthis.setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tmarkers[i].addListener('mouseout', function() {\r\n");
      out.write("\t\t\t\t\t\tthis.setAnimation(null);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tlisteners[i] = markers[i].addListener('click', function() {\r\n");
      out.write("\t\t\t\t\t\tthis.setAnimation(null);\r\n");
      out.write("\t\t\t\t\t\tshowWindow(this);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\theatMapArray[i] = markers[i].getPosition();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(request,status,error){\r\n");
      out.write("\t\t\t/* alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error); */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}, 1000);\r\n");
      out.write("\tinfoWindow = new google.maps.InfoWindow();\r\n");
      out.write("\t\r\n");
      out.write("\timage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\t\"crash.svg\",\r\n");
      out.write("\t\t    null,null,null,\r\n");
      out.write("\t\t    new google.maps.Size(25, 25)\r\n");
      out.write("\t\t);\r\n");
      out.write("\tmap.addListener('click', function(e) {\r\n");
      out.write("\t\tif(event1 != null)\r\n");
      out.write("\t\t\tevent1.setMap(null);\r\n");
      out.write("\t\tevent1 = new google.maps.Marker();\r\n");
      out.write("\t\tevent1.setPosition(e.latLng);\r\n");
      out.write("\t\tevent1.setIcon(image);\r\n");
      out.write("\t\tevent1.setMap(map);\r\n");
      out.write("\t\tevent1.setTitle(\"사건\");\r\n");
      out.write("\t\tevent1.setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function makeCircle() {\r\n");
      out.write("\tclientList = [];\r\n");
      out.write("\tradius = eval(document.getElementById('radius').value);\r\n");
      out.write("\tpeople = eval(document.getElementById('people').value);\r\n");
      out.write("\tmsg = selecMarker.getPosition().lat()+\",\"+selecMarker.getPosition().lng()+\",\"+radius+\",\"+people+\",\"+selecMarker.getTitle();\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"http://\"+address+\":8080/WebServer/DataController?type=knn&pubmsg=\" + msg,\r\n");
      out.write("\t\tdata: msg,\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tfor(var i=0; i<markers.length; i++) {\r\n");
      out.write("\t\t\t\tfor(var j=0; j<data.clients.length; j++)\r\n");
      out.write("\t\t\t\t\tif(markers[i].getTitle() == String(data.clients[j]))\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor(var k=0; k<data.clients.length; k++) {\r\n");
      out.write("\t\t\t\tclientList.push(data.clients[k]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(request,status,error){\r\n");
      out.write("\t\t\t/* alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error); */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tmyCircle = new google.maps.Circle({\r\n");
      out.write("        strokeColor: '#00FF00',\r\n");
      out.write("        strokeOpacity: 0.8,\r\n");
      out.write("        strokeWeight: 2,\r\n");
      out.write("        fillColor: '#00FF00',\r\n");
      out.write("        fillOpacity: 0.35,\r\n");
      out.write("        map: map,\r\n");
      out.write("        center: selecMarker.getPosition(),\r\n");
      out.write("        radius: radius,\r\n");
      out.write("\t\teditable : false,\r\n");
      out.write("\t\tdraggable : false\r\n");
      out.write("    });\r\n");
      out.write("\tmyCircle.setMap(map);\r\n");
      out.write("\tgoogle.maps.event.addListener(infoWindow, \"closeclick\", function(){\r\n");
      out.write("\t\tgotoInit();\r\n");
      out.write("\t});\r\n");
      out.write("\tmap.setZoom(13);\r\n");
      out.write("\tmap.setCenter(selecMarker.getPosition());\r\n");
      out.write("\tvar contentString = '<button onclick=\"openDialog(clientList)\" class=\"btn btn-primary\">메세지 보내기</button>';\r\n");
      out.write("\tinfoWindow.setContent(contentString);\r\n");
      out.write("\tinfoWindow.open(map);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function gotoInit() {\r\n");
      out.write("\tmyCircle.setMap(null);\r\n");
      out.write("\tfor(var i=0; i<markers.length; i++) {\r\n");
      out.write("\t\tif(markers[i].getAnimation() != null)\r\n");
      out.write("\t\t\tmarkers[i].setAnimation(null);\r\n");
      out.write("\t}\r\n");
      out.write("\tmap.setZoom(11.35);\r\n");
      out.write("\tmap.setCenter(new google.maps.LatLng(37.56017787685811,126.98316778778997));\r\n");
      out.write("}\r\n");
      out.write("k=0;\r\n");
      out.write("function showWindow(marker) {\r\n");
      out.write("\tconsole.log(k++);\r\n");
      out.write("\tselecMarker = marker;\r\n");
      out.write("\t/* var contentString = \"<form name='myForm'>\"+\r\n");
      out.write("\t\t\t\t\t\"<table><tr><td>&nbsp;</td></tr><tr><td align='center'>\"+\r\n");
      out.write("\t\t\t\t\t\"<span>반경 : </span></td><td><input id='radius' name='radius' type='text' class='form-control form-control-sm' value='미터 단위' onFocus='clearText(this)'/>&nbsp;<span><b>M</b></span></td></tr>\"+\r\n");
      out.write("\t\t\t\t\t\"<tr><td><span>사람 수 : </span></td><td><input id='people' name='people' type='text' class='form-control form-control-sm' value='가까운 K명 선택' onFocus='clearText(this)'/>\"+\r\n");
      out.write("\t\t\t\t\t\"&nbsp;<span><b>명</b></span></td></tr><tr><td>&nbsp;</td></tr><tr><td colspan='2' align='center'><input type='button' value='선택' onclick='makeCircle()'/></td></tr>\"+\r\n");
      out.write("\t\t\t\t\t\"<tr><td>&nbsp;</td></tr></table></form>\"; */\r\n");
      out.write("\tvar contentString = \"<form name='myForm'>\"+\r\n");
      out.write("\t\t\t\t\t\"<div class='form-group'><label for='radius'>반경 : (M)</label><input type='text' class='form-control form-control-sm' id='radius' style='width:150px' placeholder='미터 단위'></div>\"+\r\n");
      out.write("\t\t\t\t\t\"<div class='form-group'><label for='people'>사람 수 : (명)</label><input type='text' class='form-control form-control-sm' id='people' style='width:150px' placeholder='가까운 K명 선택'></div>\"+\r\n");
      out.write("\t\t\t\t\t\"<input type='button' value='선택' onclick='makeCircle()' class='btn btn-danger'/></form>\";\r\n");
      out.write("\tinfoWindow.setContent(contentString);\r\n");
      out.write("\tinfoWindow.setPosition(marker.getPosition());\r\n");
      out.write("\tinfoWindow.open(map);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openDialog(clientList) {\r\n");
      out.write("\t\tvar clientView = \"\";\r\n");
      out.write("\t\tfor(var k=0; k<clientList.length; k++) {\r\n");
      out.write("\t\t\tif(k+1 != clientList.length)\r\n");
      out.write("\t\t\t\tclientView += clientList[k] + \"<br>\";\r\n");
      out.write("\t\t\telse clientView += clientList[k];\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#dialog\").dialog({\r\n");
      out.write("\t\t\tautoOpen : false,\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tresizable : false,\r\n");
      out.write("\t\t\tshow : 'slide',\r\n");
      out.write("\t\t\thide : 'slide',\r\n");
      out.write("\t\t\tposition:{\r\n");
      out.write("              my:\"left top\",\r\n");
      out.write("              at:\"left top\",\r\n");
      out.write("              of:\"#map-canvas\" \r\n");
      out.write("              },\r\n");
      out.write("          open: function() {\r\n");
      out.write("          \t$(this).find(\"span\").eq(0).html($(this).data(\"name\"));\r\n");
      out.write("          },\r\n");
      out.write("\t\t\tbuttons : {\r\n");
      out.write("\t\t\t\t\"메시지 전송\" : function() {\r\n");
      out.write("\t\t\t\t\tvar msg = \"sp,\";\r\n");
      out.write("\t\t\t\t\t\t/* document.getElementById(\"test\").value; */\r\n");
      out.write("\t\t\t\t\tvar emergency = \"nomal\";\r\n");
      out.write("  \t\t\t\t\tif(document.getElementById(\"emergency\").checked) {\r\n");
      out.write("  \t\t\t\t\t\temergency = \"emer\";\r\n");
      out.write("  \t  \t\t\t\t\tvar eventLat = event1.getPosition().lat();\r\n");
      out.write("  \t  \t\t\t\t\tvar eventLng = event1.getPosition().lng();\r\n");
      out.write("  \t  \t\t\t\t\t\r\n");
      out.write("  \t  \t\t\t\t\tmsg = msg+emergency+\",\"+eventLat+\",\"+eventLng+\",\"+document.getElementById(\"test\").value;\r\n");
      out.write("\t  \t  \t\t\t\tvar test = msg+\",\"+clientList.length+\",\"+clientList.join(\",\");\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\turl : \"http://\"+address+\":8080/WebServer/DataController?type=publishKnn&pubmsg=\" + test,\r\n");
      out.write("\t\t\t\t\t\t\tdata: test,\r\n");
      out.write("\t\t\t\t\t\t\tdataType: \"text\",\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$.blockUI({ \r\n");
      out.write("\t\t\t\t\t            message: $(\"#block\"),\r\n");
      out.write("\t\t\t\t\t            fadeIn: 700, \r\n");
      out.write("\t\t\t\t\t            fadeOut: 700, \r\n");
      out.write("\t\t\t\t\t            timeout: 2000, \r\n");
      out.write("\t\t\t\t\t            showOverlay: false, \r\n");
      out.write("\t\t\t\t\t            centerY: false, \r\n");
      out.write("\t\t\t\t\t            css: { \r\n");
      out.write("\t\t\t\t\t                width: '350px', \r\n");
      out.write("\t\t\t\t\t                top: '70px', \r\n");
      out.write("\t\t\t\t\t                left: '', \r\n");
      out.write("\t\t\t\t\t                right: '10px', \r\n");
      out.write("\t\t\t\t\t                border: 'none', \r\n");
      out.write("\t\t\t\t\t                padding: '5px', \r\n");
      out.write("\t\t\t\t\t                backgroundColor: '#000', \r\n");
      out.write("\t\t\t\t\t                '-webkit-border-radius': '10px', \r\n");
      out.write("\t\t\t\t\t                '-moz-border-radius': '10px', \r\n");
      out.write("\t\t\t\t\t                opacity: .6, \r\n");
      out.write("\t\t\t\t\t                color: '#fff' \r\n");
      out.write("\t\t\t\t\t            } \r\n");
      out.write("\t\t\t\t\t        });\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#dialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t\t\tgotoInit();\r\n");
      out.write("\t\t\t\t\t\t\t\tinfoWindow.open(null);\r\n");
      out.write("\t\t\t\t\t\t\t\tif(event1 != null) {\r\n");
      out.write("\t  \t\t\t\t\t\t\t\tevent1.setMap(null);\r\n");
      out.write("\t  \t\t\t\t\t\t\t\tevent1 = null;\r\n");
      out.write("\t  \t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror : function(request, status, error) {\r\n");
      out.write("\t\t\t\t\t\t\t\t/* alert(\"code:\" + request.status + \"\\n\" + \"message:\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ request.responseText + \"\\n\" + \"error:\" + error); */\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\telse {\r\n");
      out.write("  \t\t\t\t\t\tmsg = msg+emergency+\",\"+document.getElementById(\"test\").value;\r\n");
      out.write("  \t\t\t\t\t\tvar test = msg+\",\"+clientList.length+\",\"+clientList.join(\",\");\r\n");
      out.write("  \t\t\t\t\t\t$.ajax({\r\n");
      out.write("  \t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("  \t\t\t\t\t\t\turl : \"http://\"+address+\":8080/WebServer/DataController?type=publishKnn&pubmsg=\" + test,\r\n");
      out.write("  \t\t\t\t\t\t\tdata: test,\r\n");
      out.write("  \t\t\t\t\t\t\tdataType: \"text\",\r\n");
      out.write("  \t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("  \t\t\t\t\t\t\t\t$.blockUI({ \r\n");
      out.write("  \t\t\t\t\t            message: $(\"#block\"),\r\n");
      out.write("  \t\t\t\t\t            fadeIn: 700, \r\n");
      out.write("  \t\t\t\t\t            fadeOut: 700, \r\n");
      out.write("  \t\t\t\t\t            timeout: 2000, \r\n");
      out.write("  \t\t\t\t\t            showOverlay: false, \r\n");
      out.write("  \t\t\t\t\t            centerY: false, \r\n");
      out.write("  \t\t\t\t\t            css: { \r\n");
      out.write("  \t\t\t\t\t                width: '350px', \r\n");
      out.write("  \t\t\t\t\t                top: '70px', \r\n");
      out.write("  \t\t\t\t\t                left: '', \r\n");
      out.write("  \t\t\t\t\t                right: '10px', \r\n");
      out.write("  \t\t\t\t\t                border: 'none', \r\n");
      out.write("  \t\t\t\t\t                padding: '5px', \r\n");
      out.write("  \t\t\t\t\t                backgroundColor: '#000', \r\n");
      out.write("  \t\t\t\t\t                '-webkit-border-radius': '10px', \r\n");
      out.write("  \t\t\t\t\t                '-moz-border-radius': '10px', \r\n");
      out.write("  \t\t\t\t\t                opacity: .6, \r\n");
      out.write("  \t\t\t\t\t                color: '#fff' \r\n");
      out.write("  \t\t\t\t\t            } \r\n");
      out.write("  \t\t\t\t\t        });\r\n");
      out.write("  \t\t\t\t\t\t\t\t$(\"#dialog\").dialog(\"close\");\r\n");
      out.write("  \t\t\t\t\t\t\t\tgotoInit();\r\n");
      out.write("  \t\t\t\t\t\t\t\tinfoWindow.open(null);\r\n");
      out.write("  \t\t\t\t\t\t\t\tif(event1 != null) {\r\n");
      out.write("\t  \t\t\t\t\t\t\t\tevent1.setMap(null);\r\n");
      out.write("\t  \t\t\t\t\t\t\t\tevent1 = null;\r\n");
      out.write("\t  \t\t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t\t\t},\r\n");
      out.write("  \t\t\t\t\t\t\terror : function(request, status, error) {\r\n");
      out.write("  \t\t\t\t\t\t\t\t/* alert(\"code:\" + request.status + \"\\n\" + \"message:\"\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t+ request.responseText + \"\\n\" + \"error:\" + error); */\r\n");
      out.write("  \t\t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"취소\" : function() {\r\n");
      out.write("\t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#dialog\").data('name', clientView).dialog('open');\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("google.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<nav class=\"col-md-2 d-none d-md-block bg-light sidebar\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-sticky\">\r\n");
      out.write("\t\t\t\t<!-- title -->\t\r\n");
      out.write("\t\t\t\t<table id=\"webTitle\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"logo.png\" width=\"50px\" height=\"50px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" id=\"webTitle\">서울시 실시간 유동인구<br>통합메시징 시스템</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t\t\t\t\t<span>Publish Msg to Clients</span>\r\n");
      out.write("\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 실시간 유동인구\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 구 단위 메시지 보내기\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 동 단위 메시지 보내기\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t<span data-feather=\"users\"></span> 관리자 지정 구역 메시지 보내기 [사각형]\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t<span data-feather=\"users\"></span> 관리자 지정 구역 메시지 보내기 [원]\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t\t\t\t\t<span>Retrieve LBS Data Report</span>\r\n");
      out.write("\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column mb-2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tdata-feather=\"bar-chart-2\"></span> DashBoard\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tdata-feather=\"layers\"></span> Tracking-Clients\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div id=\"floating-panel\">\r\n");
      out.write("\t\t\t      <button onclick=\"toggleHeatmap()\" class=\"btn btn-success\">열지도(Toggle)</button>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"map-canvas\" class=\"col-md-10\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"dialog\" title=\"긴급 메시지 보내기\" style=\"display:none\">\r\n");
      out.write("\t\t<form id=\"form\" method=\"post\">\r\n");
      out.write("\t\t\t<span></span><br><br>\r\n");
      out.write("\t\t\t<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input class=\"form-check-input\" type=\"checkbox\" id=\"emergency\">긴급 상황</p>\r\n");
      out.write("\t\t\t<input id=\"test\" name=\"test\" type=\"text\" value=\"긴급 메시지\" onFocus=\"clearText(this)\"/>\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"block\" style=\"display:none;\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td rowspan=\"2\"><img src=\"check48.png\" width=\"45px\" height=\"45px\"/></td>\r\n");
      out.write("\t\t\t\t<td><h5>&nbsp;&nbsp;<b>메시지를 보내는 중입니다.</b></h5></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><h6>Please Wait..</h6></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<!-- <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script> -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Icons -->\r\n");
      out.write("\t<script src=\"https://unpkg.com/feather-icons/dist/feather.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfeather.replace()\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /index.jsp(41,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/main.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /index.jsp(426,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/MainController?param=main");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /index.jsp(434,59) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/MainController?param=main");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /index.jsp(437,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/MainController?param=district");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /index.jsp(440,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/MainController?param=neighborhood");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /index.jsp(443,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/MainController?param=rectangle");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /index.jsp(446,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/MainController?param=circle");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /index.jsp(456,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/MainController?param=dashboard");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /index.jsp(459,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/MainController?param=tracking");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }
}
