/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2018-09-21 01:43:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class neighborhoodMsg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/mqtt/WebServer_final/WebServer/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebServer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1519644874033L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>동 단위 행정구역별 메시지 보내기</title>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link rel=\"icon\" href=\"logo.png\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDo3Hex6WnJUr6NTdUiwl9pM3CGJs7OvlA\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.3.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.0/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"jquery.blockUI.js\"></script>\r\n");
      out.write("<script src=\"main1.js\"></script>\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/earlyaccess/notosanskr.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar layer_0;\r\n");
      out.write("\tvar map;\r\n");
      out.write("\tvar markerImage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\t/* \"newmarker.png\", */\r\n");
      out.write("\t\t\t\"icon.png\",\r\n");
      out.write("\t\t    null,null,null,\r\n");
      out.write("\t\t    new google.maps.Size(10, 10)\r\n");
      out.write("\t\t);\r\n");
      out.write("\tvar carImage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\t\"sports-car.png\",\r\n");
      out.write("\t\t    null,null,null,\r\n");
      out.write("\t\t    new google.maps.Size(30, 30)\r\n");
      out.write("\t\t);\r\n");
      out.write("\tfunction initialize() {\r\n");
      out.write("\t\t/* map = new google.maps.Map(document.getElementById('map-canvas'), {\r\n");
      out.write("\t\t\tcenter : new google.maps.LatLng(37.551047990317834,\r\n");
      out.write("\t\t\t\t\t126.99372496797264),\r\n");
      out.write("\t\t\tzoom : 11,\r\n");
      out.write("\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\tvar latlng = new google.maps.LatLng(37.56017787685811,\r\n");
      out.write("\t\t\t\t126.98316778778997);\r\n");
      out.write("\t\tvar mapOptions = {\r\n");
      out.write("\t\t\t\tzoom : 11.35,\r\n");
      out.write("\t\t\t\tcenter : latlng,\r\n");
      out.write("\t\t\t\t//draggable : false,\r\n");
      out.write("\t\t\t\tscaleControl : true,\r\n");
      out.write("\t\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmap = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\r\n");
      out.write("\t\tcurrent = new google.maps.LatLng(37.5640, 126.9751);\r\n");
      out.write("\t\tmarker = new Array();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tscript = document.createElement('script');\r\n");
      out.write("        var url = ['https://www.googleapis.com/fusiontables/v1/query?'];\r\n");
      out.write("        url.push('sql=');\r\n");
      out.write("        var query = 'SELECT EMD_KOR_NM, geometry, EMD_ENG_NM FROM ' +\r\n");
      out.write("            '10pRI5kjOiqTtr7rm-vgt5_rnEOATsu2sj9vEzcMb';\r\n");
      out.write("        var encodedQuery = encodeURIComponent(query);\r\n");
      out.write("        url.push(encodedQuery);\r\n");
      out.write("        url.push('&callback=drawMap');\r\n");
      out.write("        url.push('&key=AIzaSyAm9yWCV7JPCTHCJut8whOjARd7pwROFDQ');\r\n");
      out.write("        script.src = url.join('');\r\n");
      out.write("        body = document.getElementById('map-canvas');\r\n");
      out.write("        body.appendChild(script);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlayer_0 = new google.maps.FusionTablesLayer({\r\n");
      out.write("\t\t\tquery : {\r\n");
      out.write("\t\t\t\tselect : \"col0\",\r\n");
      out.write("\t\t\t\tfrom : \"10pRI5kjOiqTtr7rm-vgt5_rnEOATsu2sj9vEzcMb\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tmap : map,\r\n");
      out.write("\t\t\tstyleId : 2,\r\n");
      out.write("\t\t\ttemplateId : 2\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttimer = setInterval( function () {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"http://\"+address+\":8080/WebServer/LocationController\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tvar latitude, longitude;\r\n");
      out.write("\t\t\t\t\tfor(var i=0; i<Object.keys(data).length; i++) {\r\n");
      out.write("\t\t\t\t\t\tclient_id = eval(\"data.c\"+i+\".client_id\");\r\n");
      out.write("\t\t\t\t\t\tlatitude = eval(\"data.c\"+i+\".latitude\");\r\n");
      out.write("\t\t\t\t\t\tlongitude = eval(\"data.c\"+i+\".longitude\");\r\n");
      out.write("\t\t\t\t\t\tvar current = new google.maps.LatLng(latitude, longitude);\r\n");
      out.write("\t\t\t\t\t\tif(marker[i]) {\r\n");
      out.write("\t\t\t\t\t\t\tmarker[i].setPosition(current);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tif (client_id == 'paho000011117') {\r\n");
      out.write("\t\t\t\t\t\t\t\tmarker[i] = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tposition : current,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : client_id,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticon : carImage\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tmarker[i] = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\t\tposition : current,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : client_id,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticon : markerImage\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(request,status,error){\r\n");
      out.write("\t\t\t\t\t/* alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error); */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}, 1000);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar countries = new Array(3);\r\n");
      out.write("\tcountries[0] = new Array(25);\r\n");
      out.write("\tcountries[1] = new Array(25);\r\n");
      out.write("\tcountries[2] = new Array(25);\r\n");
      out.write("\t\r\n");
      out.write("\tfunction drawMap(data) {\r\n");
      out.write("        /* var rows = data['rows']; */\r\n");
      out.write("        var rows = data.rows;\r\n");
      out.write("        for (var i in rows) {\r\n");
      out.write("          var newCoordinates = [];\r\n");
      out.write("          countries[0][i] = rows[i][0];\r\n");
      out.write("\t\t\tcountries[2][i] = rows[i][2];\r\n");
      out.write("\t\t\t/* var geometries = rows[i][1];\r\n");
      out.write("\t\t\tif (geometries) {\r\n");
      out.write("\t\t\t\tnewCoordinates.push(constructNewCoordinates(geometries));\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("          var geometries = rows[i][1]['geometries'];\r\n");
      out.write("          if (geometries) {\r\n");
      out.write("            for (var j in geometries) {\r\n");
      out.write("              newCoordinates.push(constructNewCoordinates(geometries[j]));\r\n");
      out.write("            }\r\n");
      out.write("          } else {\r\n");
      out.write("            newCoordinates = constructNewCoordinates(rows[i][1]['geometry']);\r\n");
      out.write("          }\r\n");
      out.write("          countries[1][i] = new google.maps.Polygon({\r\n");
      out.write("            id : i,\r\n");
      out.write("        \tpaths: newCoordinates,\r\n");
      out.write("            strokeColor: '#FF0000',\r\n");
      out.write("            strokeOpacity: 0,\r\n");
      out.write("            strokeWeight: 1,\r\n");
      out.write("            fillColor: '#FF0000',\r\n");
      out.write("            fillOpacity: 0\r\n");
      out.write("          });\r\n");
      out.write("          google.maps.event.addListener(countries[1][i], 'mouseover', function() {\r\n");
      out.write("            this.setOptions({fillOpacity: 0.6});\r\n");
      out.write("          });\r\n");
      out.write("          google.maps.event.addListener(countries[1][i], 'mouseout', function() {\r\n");
      out.write("            this.setOptions({fillOpacity: 0});\r\n");
      out.write("          });\r\n");
      out.write("          google.maps.event.addListener(countries[1][i], 'click', function() {\r\n");
      out.write("\t\t\t\topenDialog(countries[0][this.id], countries[2][this.id]);\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  countries[1][i].setMap(map);\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function constructNewCoordinates(polygon) {\r\n");
      out.write("    \t  /* var newCoordinates = [];\r\n");
      out.write("  \t\tvar comma = 0;\r\n");
      out.write("  \t\tvar lat=[];\r\n");
      out.write("  \t\tvar lang=[];\r\n");
      out.write("  \t\tvar tempLat=\"\";\r\n");
      out.write("  \t\tvar tempLang=\"\";\r\n");
      out.write("  \t\tvar two = 0;\r\n");
      out.write("  \t\tvar check = true;\r\n");
      out.write("  \t\tfor(var i in polygon) {\r\n");
      out.write("  \t\t\tif(two==1){ two=2; continue; }\r\n");
      out.write("  \t\t\tif(parseInt(i) >= polygon.length-57) break;\r\n");
      out.write("  \t\t\telse {\r\n");
      out.write("  \t\t\t\tif(polygon[parseInt(i)+51] == ',') {\r\n");
      out.write("  \t\t\t\t\tcomma++;\r\n");
      out.write("  \t\t\t\t\tif(comma%2!=0) {\r\n");
      out.write("  \t\t\t\t\t\tlang.push(parseFloat(tempLang));\r\n");
      out.write("  \t\t\t\t\t\ttempLang = \"\";\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\telse {\r\n");
      out.write("  \t\t\t\t\t\tcheck = !check;\r\n");
      out.write("  \t\t\t\t\t\tlat.push(parseFloat(tempLat));\r\n");
      out.write("  \t\t\t\t\t\ttempLat = \"\";\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\tcontinue;\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t\tif(comma%2==0) {\r\n");
      out.write("  \t\t\t\t\tif(comma >= 2) {\r\n");
      out.write("  \t\t\t\t\t\tif(!check) {\r\n");
      out.write("  \t\t\t\t\t\t\tswitch(two) {\r\n");
      out.write("  \t\t\t\t\t\t\t\tcase 0: two = 1; break;\r\n");
      out.write("  \t\t\t\t\t\t\t\tcase 2: two = 0; break;\r\n");
      out.write("  \t\t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t\t\tif(two==1) continue;\r\n");
      out.write("  \t\t\t\t\t\t\tcheck = !check;\r\n");
      out.write("  \t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\ttempLang += polygon[parseInt(i)+51];\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t\telse {\r\n");
      out.write("  \t\t\t\t\ttempLat += polygon[parseInt(i)+51];\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\t\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\tfor(var k in lat) {\r\n");
      out.write("  \t\t\tnewCoordinates.push(new google.maps.LatLng(lat[k], lang[k]));\r\n");
      out.write("  \t\t\tconsole.log(\"test\"+k);\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t\treturn newCoordinates; */\r\n");
      out.write("        var newCoordinates = [];\r\n");
      out.write("        var coordinates = polygon['coordinates'][0];\r\n");
      out.write("        for (var i in coordinates) {\r\n");
      out.write("          newCoordinates.push(\r\n");
      out.write("              new google.maps.LatLng(coordinates[i][1], coordinates[i][0]));\r\n");
      out.write("        }\r\n");
      out.write("        return newCoordinates;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      function openDialog(geo1, geo2) {\r\n");
      out.write("  \t\t$(\"#dialog\").dialog({\r\n");
      out.write("  \t\t\tautoOpen : false,\r\n");
      out.write("  \t\t\tmodal : true,\r\n");
      out.write("  \t\t\tresizable : false,\r\n");
      out.write("  \t\t\tshow : 'slide',\r\n");
      out.write("  \t\t\thide : 'slide',\r\n");
      out.write("  \t\t\tposition:{\r\n");
      out.write("                  my:\"left top\",\r\n");
      out.write("                  at:\"left top\",\r\n");
      out.write("                  of:\"#map-canvas\" \r\n");
      out.write("                  },\r\n");
      out.write("              open: function() {\r\n");
      out.write("              \t$(this).find(\"span\").eq(0).html($(this).data(\"name\"));\r\n");
      out.write("              },\r\n");
      out.write("  \t\t\tbuttons : {\r\n");
      out.write("  \t\t\t\t\"메시지 전송\" : function() {\r\n");
      out.write("  \t\t\t\t\tvar msg = document.getElementById(\"test\").value;\r\n");
      out.write("  \t\t\t\t\tvar test = geo2+\",\"+msg;\r\n");
      out.write("  \t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t$.ajax({\r\n");
      out.write("  \t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("  \t\t\t\t\t\turl : \"http://\"+address+\":8080/WebServer/DataController?type=district&pubmsg=\" + test,\r\n");
      out.write("  \t\t\t\t\t\tdata: test,\r\n");
      out.write("  \t\t\t\t\t\tdataType:\"text\",\r\n");
      out.write("  \t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("  \t\t\t\t\t\t\t$.blockUI({ \r\n");
      out.write("\t\t\t\t\t            //message: $('div.growlUI'),\r\n");
      out.write("\t\t\t\t\t            message: $(\"#block\"),\r\n");
      out.write("\t\t\t\t\t            fadeIn: 700, \r\n");
      out.write("\t\t\t\t\t            fadeOut: 700, \r\n");
      out.write("\t\t\t\t\t            timeout: 2000, \r\n");
      out.write("\t\t\t\t\t            showOverlay: false, \r\n");
      out.write("\t\t\t\t\t            centerY: false, \r\n");
      out.write("\t\t\t\t\t            css: { \r\n");
      out.write("\t\t\t\t\t                width: '350px', \r\n");
      out.write("\t\t\t\t\t                top: '70px', \r\n");
      out.write("\t\t\t\t\t                left: '', \r\n");
      out.write("\t\t\t\t\t                right: '10px', \r\n");
      out.write("\t\t\t\t\t                border: 'none', \r\n");
      out.write("\t\t\t\t\t                padding: '5px', \r\n");
      out.write("\t\t\t\t\t                backgroundColor: '#000', \r\n");
      out.write("\t\t\t\t\t                '-webkit-border-radius': '10px', \r\n");
      out.write("\t\t\t\t\t                '-moz-border-radius': '10px', \r\n");
      out.write("\t\t\t\t\t                opacity: .6, \r\n");
      out.write("\t\t\t\t\t                color: '#fff' \r\n");
      out.write("\t\t\t\t\t            } \r\n");
      out.write("\t\t\t\t\t        });\r\n");
      out.write("  \t\t\t\t\t\t\t$(\"#dialog\").dialog(\"close\");\r\n");
      out.write("  \t\t\t\t\t\t},\r\n");
      out.write("  \t\t\t\t\t\terror : function(request, status, error) {\r\n");
      out.write("  \t\t\t\t\t\t\t/* alert(\"code:\" + request.status + \"\\n\" + \"message:\"\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t+ request.responseText + \"\\n\" + \"error:\" + error); */\r\n");
      out.write("  \t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t});\r\n");
      out.write("  \t\t\t\t},\r\n");
      out.write("  \t\t\t\t\"취소\" : function() {\r\n");
      out.write("  \t\t\t\t\t$(this).dialog(\"close\");\r\n");
      out.write("  \t\t\t\t}\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t});\r\n");
      out.write("  \t\t$(\"#dialog\").data('name', geo1).dialog('open');\r\n");
      out.write("  \t}\r\n");
      out.write("\tgoogle.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<nav class=\"col-md-2 d-none d-md-block bg-light sidebar\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-sticky\">\r\n");
      out.write("\t\t\t\t<!-- title -->\t\r\n");
      out.write("\t\t\t\t<table id=\"webTitle\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"logo.png\" width=\"50px\" height=\"50px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" id=\"webTitle\">서울시 실시간 유동인구<br>통합메시징 시스템</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t\t\t\t\t<span>Publish Msg to Clients</span>\r\n");
      out.write("\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 실시간 유동인구\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 구 단위 메시지 보내기\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 동 단위 메시지 보내기\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t<span data-feather=\"users\"></span> 관리자 지정 구역 메시지 보내기 [사각형]\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t<span data-feather=\"users\"></span> 관리자 지정 구역 메시지 보내기 [원]\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t\t\t\t\t<span>Retrieve LBS Data Report</span>\r\n");
      out.write("\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column mb-2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tdata-feather=\"bar-chart-2\"></span> DashBoard\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tdata-feather=\"layers\"></span> Tracking-Clients\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div id=\"map-canvas\" class=\"col-md-10\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"dialog\" title=\"메시지 보내기\" style=\"display:none\">\r\n");
      out.write("\t\t<form id=\"form\" method=\"post\">\r\n");
      out.write("\t\t\t<span></span><br><br>\r\n");
      out.write("\t\t\t<input id=\"test\" name=\"test\" type=\"text\"/>\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"block\" style=\"display:none;\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td rowspan=\"2\"><img src=\"check48.png\" width=\"45px\" height=\"45px\"/></td>\r\n");
      out.write("\t\t\t\t<td><h5>&nbsp;&nbsp;<b>메시지를 보내는 중입니다.</b></h5></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><h6>Please Wait..</h6></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t<!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("\t<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("\t<!-- <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script> -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Icons -->\r\n");
      out.write("\t<script src=\"https://unpkg.com/feather-icons/dist/feather.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfeather.replace()\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /neighborhoodMsg.jsp(25,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/main.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /neighborhoodMsg.jsp(304,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/MainController?param=main");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /neighborhoodMsg.jsp(311,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/MainController?param=main");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /neighborhoodMsg.jsp(314,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/MainController?param=district");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /neighborhoodMsg.jsp(317,59) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/MainController?param=neighborhood");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /neighborhoodMsg.jsp(320,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/MainController?param=rectangle");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /neighborhoodMsg.jsp(323,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/MainController?param=circle");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /neighborhoodMsg.jsp(333,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/MainController?param=dashboard");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /neighborhoodMsg.jsp(336,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/MainController?param=tracking");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }
}
