/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2018-09-20 08:21:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tracking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/mqtt/WebServer_final/WebServer/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebServer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1519644874033L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Test Main Page</title>\r\n");
      out.write("<link rel=\"icon\" href=\"logo.png\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.3.min.js\"></script>\r\n");
      out.write("<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDo3Hex6WnJUr6NTdUiwl9pM3CGJs7OvlA&libraries=visualization\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.0/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"jquery.blockUI.js\"></script>\r\n");
      out.write("<script src=\"main1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/earlyaccess/notosanskr.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"datepicker.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Include English language -->\r\n");
      out.write("<script src=\"datepicker.en.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".required {\r\n");
      out.write("  color:red; \r\n");
      out.write("  font-weight:bold\r\n");
      out.write("}\r\n");
      out.write(".datepicker{z-index:1151 !important;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var selecMarker;\r\n");
      out.write("function clearText(y){ \r\n");
      out.write("\tif (y.defaultValue==y.value) \r\n");
      out.write("\t\ty.value = \"\" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var map;\r\n");
      out.write("var markers;\r\n");
      out.write("var checkTitle;\r\n");
      out.write("var toggleFlag = 0;\r\n");
      out.write("var pathPolyline;\r\n");
      out.write("var listeners = [];\r\n");
      out.write("var markerImage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\"newmarker.png\",\r\n");
      out.write("\t    null,null,null,\r\n");
      out.write("\t    new google.maps.Size(17, 24)\r\n");
      out.write("\t);\r\n");
      out.write("var carImage = new google.maps.MarkerImage(\r\n");
      out.write("\t\t\"sports-car.png\",\r\n");
      out.write("\t    null,null,null,\r\n");
      out.write("\t    new google.maps.Size(30, 30)\r\n");
      out.write("\t);\r\n");
      out.write("function initialize() {\r\n");
      out.write("\tvar latlng = new google.maps.LatLng(37.56017787685811,\r\n");
      out.write("\t\t\t126.98316778778997);\r\n");
      out.write("\tvar mapOptions = {\r\n");
      out.write("\t\t\tzoom : 11.35,\r\n");
      out.write("\t\t\tcenter : latlng,\r\n");
      out.write("\t\t\t//scrollwheel : true,\r\n");
      out.write("\t\t\t//draggable : false,\r\n");
      out.write("\t\t\tscaleControl : true,\r\n");
      out.write("\t\t\tmapTypeId : google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t}\r\n");
      out.write("\tmap = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\r\n");
      out.write("\t\r\n");
      out.write("\tcurrent = new google.maps.LatLng(37.5640, 126.9751);\r\n");
      out.write("\tmarkers = new Array();\r\n");
      out.write("\ttimer = setInterval( function () {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"http://\"+address+\":8080/WebServer/LocationController\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t/* console.log(heatMapArray.length + \"==================== 1\"); */\r\n");
      out.write("\t\t\tif(listeners.length != 0) {\r\n");
      out.write("\t\t\t\tfor(var i=0; i<Object.keys(data).length; i++) {\r\n");
      out.write("\t\t\t\t\tlisteners[i].remove();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar latitude, longitude;\r\n");
      out.write("\t\t\tfor(var i=0; i<Object.keys(data).length; i++) {\r\n");
      out.write("\t\t\t\tclient_id = eval(\"data.c\"+i+\".client_id\");\r\n");
      out.write("\t\t\t\tlatitude = eval(\"data.c\"+i+\".latitude\");\r\n");
      out.write("\t\t\t\tlongitude = eval(\"data.c\"+i+\".longitude\");\r\n");
      out.write("\t\t\t\tvar current = new google.maps.LatLng(latitude, longitude);\r\n");
      out.write("\t\t\t\tif(toggleFlag == 1) {\r\n");
      out.write("\t\t\t\t\tif(markers[i] && checkTitle != markers[i].getTitle()) {\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].setMap(null);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\tif(markers[i]) {\r\n");
      out.write("\t\t\t\t\t\tif(!markers[i].getMap()) {\r\n");
      out.write("\t\t\t\t\t\t\tmarkers[i].setMap(map);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tmarkers[i].setPosition(current);\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tif (client_id == 'paho000011117') {\r\n");
      out.write("\t\t\t\t\t\t\tmarkers[i] = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\tposition : current,\r\n");
      out.write("\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : client_id,\r\n");
      out.write("\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : carImage\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tmarkers[i] = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\tposition : current,\r\n");
      out.write("\t\t\t\t\t\t\t\tmap : map,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : client_id,\r\n");
      out.write("\t\t\t\t\t\t\t\tanimation : google.maps.Animation.DROP,\r\n");
      out.write("\t\t\t\t\t\t\t\ticon : markerImage\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tmarkers[i].addListener('mouseover', function() {\r\n");
      out.write("\t\t\t\t\t\tthis.setAnimation(google.maps.Animation.BOUNCE);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tmarkers[i].addListener('mouseout', function() {\r\n");
      out.write("\t\t\t\t\t\tthis.setAnimation(null);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tlisteners[i] = markers[i].addListener('click', function() {\r\n");
      out.write("\t\t\t\t\t\tthis.setAnimation(null);\r\n");
      out.write("\t\t\t\t\t\tshowWindow(this);\r\n");
      out.write("\t\t\t\t\t\tcheckTitle = this.getTitle();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(request,status,error){\r\n");
      out.write("\t\t\t/* alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error); */\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t}, 1000);\r\n");
      out.write("\tinfoWindow = new google.maps.InfoWindow();\r\n");
      out.write("\t// Initialization\r\n");
      out.write("\tmyDate = $('#startdate').datepicker({\r\n");
      out.write("\t\tstartDate : new Date(),\r\n");
      out.write("\t\tlanguage : 'en',\r\n");
      out.write("\t\tmaxDate : new Date(),\r\n");
      out.write("\t\trange : true,\r\n");
      out.write("\t\tdateFormat : \"yyyy/mm/dd\",\r\n");
      out.write("\t\tmultipleDatesSeparator : ' ~ '\r\n");
      out.write("\t}).data('datepicker');\r\n");
      out.write("\t\r\n");
      out.write("\t/* $('#enddate').datepicker({\r\n");
      out.write("\t\tstartDate : new Date(),\r\n");
      out.write("\t\tlanguage : 'en',\r\n");
      out.write("\t\tmaxDate : new Date(),\r\n");
      out.write("\t\tdateFormat : \"yyyy/mm/dd\"\r\n");
      out.write("\t}) */\r\n");
      out.write("\t// Access instance of plugin\r\n");
      out.write("\t\r\n");
      out.write("\t/* $('#enddate').data('datepicker') */\r\n");
      out.write("\t/* $('#myModal').css ('z-index', 0);  */\r\n");
      out.write("}\r\n");
      out.write("function toggle() {\r\n");
      out.write("\ttoggleFlag = 0;\r\n");
      out.write("\tmap.setZoom(11.35);\r\n");
      out.write("\tmap.setCenter(new google.maps.LatLng(37.56017787685811,126.98316778778997));\r\n");
      out.write("\tpathPolyline.setMap(null);\r\n");
      out.write("}\r\n");
      out.write("function getLog() {\r\n");
      out.write("\t$('#myModal').modal('toggle');\r\n");
      out.write("\ttoggleFlag = 1;\r\n");
      out.write("\tvar dates = myDate.selectedDates;\r\n");
      out.write("\tvar start, end;\r\n");
      out.write("\tvar startHours, startMinute, startMonth, startDate, endHours, endMinute, endMonth, endDate;\r\n");
      out.write("\tif(dates[0].getHours() == 0 || dates[0].getHours() < 10)\r\n");
      out.write("\t\tstartHours = \"0\"+dates[0].getHours();\r\n");
      out.write("\telse startHours = dates[0].getHours();\r\n");
      out.write("\tif(dates[0].getMinutes() == 0 || dates[0].getMinutes() < 10)\r\n");
      out.write("\t\tstartMinute = \"0\"+dates[0].getMinutes();\r\n");
      out.write("\telse startMinute = dates[0].getMinutes();\r\n");
      out.write("\tif(dates[1].getHours() == 0 || dates[1].getHours() < 10)\r\n");
      out.write("\t\tendHours = \"0\"+dates[1].getHours();\r\n");
      out.write("\telse endHours = dates[1].getHours();\r\n");
      out.write("\tif(dates[1].getMinutes() == 0 || dates[1].getMinutes() < 10)\r\n");
      out.write("\t\tendMinute = \"0\"+dates[1].getMinutes();\r\n");
      out.write("\telse endMinute = dates[1].getMinutes();\r\n");
      out.write("\tif(dates[0].getMonth()+1 < 10)\r\n");
      out.write("\t\tstartMonth = \"0\"+(dates[0].getMonth()+1);\r\n");
      out.write("\telse startMonth = dates[0].getMonth()+1;\r\n");
      out.write("\tif(dates[0].getDate() < 10)\r\n");
      out.write("\t\tstartDate = \"0\"+dates[0].getDate();\r\n");
      out.write("\telse startDate = dates[0].getDate();\r\n");
      out.write("\tif(dates[1].getMonth()+1 < 10)\r\n");
      out.write("\t\tendMonth = \"0\"+(dates[1].getMonth()+1);\r\n");
      out.write("\telse endMonth = dates[0].getMonth()+1;\r\n");
      out.write("\tif(dates[1].getDate() < 10)\r\n");
      out.write("\t\tendDate = \"0\"+dates[1].getDate();\r\n");
      out.write("\telse endDate = dates[1].getDate();\r\n");
      out.write("\tstart = dates[0].getFullYear().toString()+startMonth+startDate+startHours+startMinute;\r\n");
      out.write("\tend =  dates[1].getFullYear().toString()+endMonth+endDate+endHours+endMinute;\r\n");
      out.write("\tmsg = selecMarker.getTitle()+\",\"+start+\",\"+end;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"POST\",\r\n");
      out.write("\t\turl:\"http://\"+address+\":8080/WebServer/DataController?type=tracking&pubmsg=\" + msg,\r\n");
      out.write("\t\tdata: msg,\r\n");
      out.write("\t\tdataType:\"json\",\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar latitude, longitude, time;\r\n");
      out.write("\t\t\tvar pathArray = [];\r\n");
      out.write("\t\t\tvar pathMarkers = [];\r\n");
      out.write("\t\t\tvar lineSymbol = {\r\n");
      out.write("\t\t\t\t\tpath : google.maps.SymbolPath.FORWARD_CLOSED_ARROW\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tfor(var i=0; i<Object.keys(data).length; i++) {\r\n");
      out.write("\t\t\t\tlatitude = eval(\"data.d\"+i+\".latitude\");\r\n");
      out.write("\t\t\t\tlongitude = eval(\"data.d\"+i+\".longitude\");\r\n");
      out.write("\t\t\t\ttime = eval(\"data.d\"+i+\".time\");\r\n");
      out.write("\t\t\t\tvar tempLatLng = new google.maps.LatLng(latitude, longitude);\r\n");
      out.write("\t\t\t\tpathArray.push(tempLatLng);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tpathPolyline = new google.maps.Polyline({\r\n");
      out.write("\t\t\t    path: pathArray,\r\n");
      out.write("\t\t\t    geodesic: true,\r\n");
      out.write("\t\t\t    strokeColor: '#FF0000',\r\n");
      out.write("\t\t\t    strokeOpacity: 1.0,\r\n");
      out.write("\t\t\t    strokeWeight: 3,\r\n");
      out.write("\t\t\t    icons : [{\r\n");
      out.write("\t\t\t    \ticon : lineSymbol,\r\n");
      out.write("\t\t\t    \toffset: '100%'\r\n");
      out.write("\t\t\t    }]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tpathPolyline.setMap(map);\r\n");
      out.write("\t\t\tmap.setZoom(13);\r\n");
      out.write("\t\t\tmap.setCenter(selecMarker.getPosition());\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(request,status,error){\r\n");
      out.write("\t\t\talert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("k=0;\r\n");
      out.write("function showWindow(marker) {\r\n");
      out.write("\tconsole.log(k++);\r\n");
      out.write("\tselecMarker = marker;\r\n");
      out.write("\tvar contentString = \"<button type='button' class='btn btn-success' data-toggle='modal' data-target='#myModal' onclick='closeWindow()'>\"+\r\n");
      out.write("\t\t\t\t\t\t\"Start Tracking!!</button>\";\r\n");
      out.write("\tinfoWindow.setContent(contentString);\r\n");
      out.write("\tinfoWindow.setPosition(marker.getPosition());\r\n");
      out.write("\tinfoWindow.open(map);\r\n");
      out.write("}\r\n");
      out.write("function closeWindow() {\r\n");
      out.write("\tconsole.log(\"닫힘\");\r\n");
      out.write("\tinfoWindow.close();\r\n");
      out.write("}\r\n");
      out.write("/* <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("Start Tracking!!\r\n");
      out.write("</button> */\r\n");
      out.write("google.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<nav class=\"col-md-2 d-none d-md-block bg-light sidebar\">\r\n");
      out.write("\t\t\t<div class=\"sidebar-sticky\">\r\n");
      out.write("\t\t\t\t<!-- title -->\t\r\n");
      out.write("\t\t\t\t<table id=\"webTitle\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"logo.png\" width=\"50px\" height=\"50px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" id=\"webTitle\">서울시 실시간 유동인구<br>통합메시징 시스템</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t\t\t\t\t<span>Publish Msg to Clients</span>\r\n");
      out.write("\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 실시간 유동인구\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 구 단위 메시지 보내기\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<span data-feather=\"home\"></span> 동 단위 메시지 보내기\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t<span data-feather=\"users\"></span> 관리자 지정 구역 메시지 보내기 [사각형]\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t<span data-feather=\"users\"></span> 관리자 지정 구역 메시지 보내기 [원]\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h6 class=\"sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted\">\r\n");
      out.write("\t\t\t\t\t<span>Retrieve LBS Data Report</span>\r\n");
      out.write("\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column mb-2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tdata-feather=\"bar-chart-2\"></span> DashBoard\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\" href=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tdata-feather=\"layers\"></span> Tracking-Clients\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<div id=\"floating-panel\">\r\n");
      out.write("\t\t\t      <button onclick=\"toggle()\" class=\"btn btn-success\">돌아가기</button>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"map-canvas\" class=\"col-md-10\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("  <!-- The Modal -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("      \r\n");
      out.write("        <!-- Modal Header -->\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <h4 class=\"modal-title\">Tracking Clients</h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal body -->\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("        \t<span class=\"required\">추적 시간 설정</span><br><br>\r\n");
      out.write("        \t<input type=\"text\" data-timepicker=\"true\" data-time-format=\"hh:ii aa\" class=\"datepicker-here\" id=\"startdate\"\r\n");
      out.write("        \t\tonFocus='clearText(this)' value=\"클릭해서 날짜 범위를 지정하세요.\" style='width:400px'/>\r\n");
      out.write("        \t<!-- ~\r\n");
      out.write("        \t<input type=\"text\" data-timepicker=\"true\" data-time-format=\"hh:ii aa\" class=\"datepicker-here\" id=\"enddate\"/> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Modal footer -->\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-secondary\" onclick='getLog()'>확인</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Icons -->\r\n");
      out.write("\t<script src=\"https://unpkg.com/feather-icons/dist/feather.min.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfeather.replace()\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /tracking.jsp(33,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/main.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /tracking.jsp(35,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/datepicker.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /tracking.jsp(282,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/MainController?param=main");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /tracking.jsp(289,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/MainController?param=main");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /tracking.jsp(292,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/MainController?param=district");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /tracking.jsp(295,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/MainController?param=neighborhood");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /tracking.jsp(298,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/MainController?param=rectangle");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /tracking.jsp(301,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/MainController?param=circle");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /tracking.jsp(311,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/MainController?param=dashboard");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /tracking.jsp(314,59) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/MainController?param=tracking");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }
}
